### ISSUE TITLE
NPE storing file with single quotation mark in title

### ISSUE THREAD

**Issue by svub** [groovesquid/groovesquid#24]
At least that's how it seems like, as all other files from the playlist I was loading worked nicely.
The failing files name is "London's Calling" - it downloads to 100% and then showing "Error".

Nevertheless, thanks a bunch for this great piece of software! :)

Groovesquid v 0.7
Stack trace:
java.lang.NullPointerException
	at groovesquid.model.FileStore.writeTrackInfo(FileStore.java:101)
	at groovesquid.service.DownloadService$DownloadTask.download(DownloadService.java:327)
	at groovesquid.service.DownloadService$DownloadTask.run(DownloadService.java:250)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

**Comment by gbhrdt** [comment]
Thanks, just fixed it: http://puu.sh/eBM23/1367b4c9a8.png
I'll create a new push request soon.

**Comment by svub** [comment]
Beautiful, thank you!
