### ISSUE TITLE
"Play" function not working

### ISSUE THREAD

**Issue by T-Cubed** [groovesquid/groovesquid#28]
I can search for songs, and download them, but I cannot listen to them via Groovesquid (it's nice to preview the song in case it's not the version I want).

I am using Lubuntu 14.04.  I'm not an expert, so I'm not sure where the log file is kept, therefore I'm missed the first part of the log after initiating "Play" on the GUI and have copied what I could from the terminal (there is so much text being created after hitting "Play" that the terminal doesn't cache it all).  If that information is vital, please let me know how to capture/find the log so I can send you the complete information.

Here's what appears (over and over) in the terminal when I try to play a song, until the song time has run out (if I hit pause, I can see time advancing on the song - very quickly).

source not supported
java.lang.IllegalArgumentException: Master Gain not supported
	at org.classpath.icedtea.pulseaudio.PulseAudioLine.getControl(PulseAudioLine.java:89)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.getControl(PulseAudioSourceDataLine.java:51)
	at javazoom.jl.player.JavaSoundAudioDevice.setLineGain(JavaSoundAudioDevice.java:216)
	at javazoom.jl.player.MP3Player.setGain(MP3Player.java:285)
	at javazoom.jl.player.PlayThread.setGain(PlayThread.java:133)
	at groovesquid.service.PlayService.setGain(PlayService.java:313)
	at groovesquid.service.PlayService.access$700(PlayService.java:16)
	at groovesquid.service.PlayService$PlayThreadListener.positionChanged(PlayService.java:351)
	at javazoom.jl.player.PlayThread$LocalPlaybackListener.positionChanged(PlayThread.java:155)
	at javazoom.jl.player.MP3Player.firePositionChangedEvent(MP3Player.java:274)
	at javazoom.jl.player.MP3Player.play(MP3Player.java:186)
	at javazoom.jl.player.MP3Player.play(MP3Player.java:148)
	at javazoom.jl.player.PlayThread.run(PlayThread.java:90)
Mar 17, 2015 8:51:34 AM groovesquid.service.PlayService$PlayThreadListener playbackFinished
INFO: playback finished: groovesquid.model.Track@e76fcc
Mar 17, 2015 8:51:34 AM groovesquid.service.PlayService skipToNext
INFO: skipped beyond end of playlist
thread ends

Please advise. :-)

PS: If you need what happens at the startup, here's that text:

Mar 17, 2015 9:01:15 AM groovesquid.Main main
INFO: Groovesquid v0.7.0 running on OpenJDK Client VM 1.7.0_75-b13 (Oracle Corporation) in /usr/lib/jvm/java-7-openjdk-i386/jre
Mar 17, 2015 9:01:19 AM groovesquid.InitThread <init>
INFO: Initializing...
Mar 17, 2015 9:01:19 AM groovesquid.Grooveshark sendRequest
INFO: >>> {"header":{"client":"htmlshark","clientRevision":"20130520","privacy":"0","uuid":"f668c95b-8892-477a-a0e8-b07910169e81","country":{"IPR":"1","ID":"223","CC1":"0","CC2":"0","CC3":"0","CC4":"2147483648"}},"method":"initiateSession"}
Mar 17, 2015 9:01:19 AM groovesquid.Grooveshark sendRequest
INFO: <<< {"header":{"serviceVersion":"20100903","prefetchEnabled":true,"session":"3e807e19bd32b9662422e245d77c4a0d"},"result":"3e807e19bd32b9662422e245d77c4a0d"}
Mar 17, 2015 9:01:19 AM groovesquid.Grooveshark setSession
INFO: session: 3e807e19bd32b9662422e245d77c4a0d
Mar 17, 2015 9:01:19 AM groovesquid.Grooveshark sendRequest
INFO: >>> {"header":{"client":"htmlshark","token":"9010f534796dad58aca28f53903591055213ab6e78b71d","session":"3e807e19bd32b9662422e245d77c4a0d","clientRevision":"20130520","privacy":"0","uuid":"f668c95b-8892-477a-a0e8-b07910169e81","country":{"IPR":"1","ID":"223","CC1":"0","CC2":"0","CC3":"0","CC4":"2147483648"}},"parameters":{"secretKey":"d9ce9bc34f4a91a8b1e4cbaf3c6f17f5"},"method":"getCommunicationToken"}
Mar 17, 2015 9:01:19 AM groovesquid.GetAdsThread getFile
SEVERE: null
java.lang.RuntimeException: http://groovesquid.com/ads/inc/api.php?getAds
	at groovesquid.GetAdsThread.getFile(GetAdsThread.java:91)
	at groovesquid.GetAdsThread.run(GetAdsThread.java:49)

Mar 17, 2015 9:01:19 AM groovesquid.UpdateCheckThread getFile
SEVERE: null
java.lang.RuntimeException: http://groovesquid.com/updatecheck.php
	at groovesquid.UpdateCheckThread.getFile(UpdateCheckThread.java:86)
	at groovesquid.UpdateCheckThread.run(UpdateCheckThread.java:53)

Exception in thread "Thread-2" java.lang.NullPointerException
	at groovesquid.GetAdsThread.run(GetAdsThread.java:50)
Exception in thread "Thread-3" java.lang.NullPointerException
	at groovesquid.UpdateCheckThread.run(UpdateCheckThread.java:54)
Mar 17, 2015 9:01:20 AM groovesquid.Grooveshark sendRequest
INFO: <<< {"header":{"session":"3e807e19bd32b9662422e245d77c4a0d","serviceVersion":"20100903","prefetchEnabled":true},"result":"caae477f81487b14c76a827ccbc83a9ee34262c3"}
Mar 17, 2015 9:01:20 AM groovesquid.Grooveshark setCommtoken
INFO: commtoken: caae477f81487b14c76a827ccbc83a9ee34262c3
Mar 17, 2015 9:01:20 AM groovesquid.Grooveshark sendRequest
INFO: >>> {"header":{"client":"jsqueue","token":"9354fa48cff37d084f88655e309889aaaebd81850966de","session":"3e807e19bd32b9662422e245d77c4a0d","clientRevision":"20130520","privacy":"0","uuid":"f668c95b-8892-477a-a0e8-b07910169e81","country":{"IPR":"1","ID":"223","CC1":"0","CC2":"0","CC3":"0","CC4":"2147483648"}},"method":"getCountry"}
Mar 17, 2015 9:01:20 AM groovesquid.Grooveshark sendRequest
INFO: <<< {"header":{"session":"3e807e19bd32b9662422e245d77c4a0d"},"fault":{"code":1024,"message":" invalid client"}}

**Comment by gbhrdt** [comment]
There seems to be a bug in OpenJDK (see https://bugs.launchpad.net/ubuntu/+source/openjdk-6/+bug/625790) and Ubuntu..
You could try the JRE by Oracle instead. See http://wiki.ubuntuusers.de/Java/Installation/Oracle_Java/Java_7

**Comment by T-Cubed** [comment]
Installing Oracle JDK 7 fixed it!  Thanks!!!
