### ISSUE TITLE
Crashing on launch

### ISSUE THREAD

**Issue by voldyman** [groovesquid/groovesquid#33]
i am trying to run GrooveSquid on Fedora 21
this is the output of the crash
```
Apr 12, 2015 4:20:26 AM com.groovesquid.Main main
INFO: Groovesquid v0.8.0 running on OpenJDK 64-Bit Server VM 1.8.0_40-b25 (Oracle Corporation) in /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.40-24.b25.fc21.x86_64/jre
Apr 12, 2015 4:20:26 AM com.groovesquid.GroovesharkClient$InitTask <init>
INFO: initializing...
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at com.groovesquid.GroovesharkClient$InitTask$2.run(GroovesharkClient.java:259)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Apr 12, 2015 4:20:29 AM com.groovesquid.GroovesharkClient init
INFO: session: 0623492fasc72e101bc95137cc513d7a
Apr 12, 2015 4:20:29 AM com.groovesquid.GroovesharkClient init
INFO: commToken: 476c5ed9b5981cd41d6ad20cde534142fabd4953
Apr 12, 2015 4:20:29 AM com.groovesquid.GroovesharkClient init
INFO: country: ID: 101, CC1: 0, CC2: 68719476736, CC3: 0, CC4: 0, DMA: 0, iso: null, region: null, city: null, zip: null, IPR: 0
```

**Comment by gbhrdt** [comment]
It seems to me, that `GraphicsEnvironment.isHeadless()` in `Groovesquid.java` returns the wrong value. I'll look into it!

**Comment by voldyman** [comment]
Turns out fedora by default has the headless installed, installing the correct package fixed my issue.
