### ISSUE TITLE
error download track com.groovesquid.model.Track@XXX

### ISSUE THREAD

**Issue by infinitnet** [groovesquid/groovesquid#41]
Having issues with the new 0.9.0 version, downloads are not working anymore.

```
$ java -jar Groovesquid.jar
Mai 13, 2015 1:03:10 PM com.groovesquid.Groovesquid main
INFORMATION: Groovesquid v0.9.0 running on Java HotSpot(TM) 64-Bit Server VM 1.7.0_80-b15 (Oracle Corporation) in /usr/lib/jvm/java-7-oracle/jre
Mai 13, 2015 1:03:12 PM com.groovesquid.util.I18n load
INFORMATION: Loading language files!
Mai 13, 2015 1:03:12 PM com.groovesquid.util.I18n load
INFORMATION: Loading local translations!
Mai 13, 2015 1:03:12 PM com.groovesquid.util.I18n load
INFORMATION: Loaded the following languages: [af, ca, da, de, en_PT, en_US, es_ES, fr, it, hu, lol, nl, nl_BE, no, pl, pt_BR, pt_PT, ro, fi, sv_SE, vi, tr, cs, el, ru, sr, uk, iw, ar, th, zh_CN, zh_TW, ja, ko]
Mai 13, 2015 1:03:46 PM com.groovesquid.service.DownloadService$DownloadTask run
SCHWERWIEGEND: error download track com.groovesquid.model.Track@473e0d3d
java.lang.UnsupportedOperationException: Not an object: null
	at com.eclipsesource.json.JsonValue.asObject(JsonValue.java:282)
	at com.groovesquid.service.extractor.NeteaseExtractor.getDownloadUrl(NeteaseExtractor.java:57)
	at com.groovesquid.service.ExtractorService.getDownloadUrl(ExtractorService.java:24)
	at com.groovesquid.service.DownloadService$DownloadTask.run(DownloadService.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

```
$ /usr/lib/jvm/java-8-oracle/jre/bin/java -jar Groovesquid.jar
Mai 13, 2015 1:04:49 PM com.groovesquid.Groovesquid main
INFORMATION: Groovesquid v0.9.0 running on Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14 (Oracle Corporation) in /usr/lib/jvm/java-8-oracle/jre
Mai 13, 2015 1:04:50 PM com.groovesquid.util.I18n load
INFORMATION: Loading language files!
Mai 13, 2015 1:04:50 PM com.groovesquid.util.I18n load
INFORMATION: Loading local translations!
Mai 13, 2015 1:04:50 PM com.groovesquid.util.I18n load
INFORMATION: Loaded the following languages: [af, ca, da, de, en_PT, en_US, es_ES, fr, it, hu, lol, nl, nl_BE, no, pl, pt_BR, pt_PT, ro, fi, sv_SE, vi, tr, cs, el, ru, sr, uk, iw, ar, th, zh_CN, zh_TW, ja, ko]
Mai 13, 2015 1:05:00 PM com.groovesquid.service.DownloadService$DownloadTask run
SCHWERWIEGEND: error download track com.groovesquid.model.Track@2a49d988
java.lang.UnsupportedOperationException: Not an object: null
	at com.eclipsesource.json.JsonValue.asObject(JsonValue.java:282)
	at com.groovesquid.service.extractor.NeteaseExtractor.getDownloadUrl(NeteaseExtractor.java:57)
	at com.groovesquid.service.ExtractorService.getDownloadUrl(ExtractorService.java:24)
	at com.groovesquid.service.DownloadService$DownloadTask.run(DownloadService.java:196)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by gbhrdt** [comment]
Does version 0.9.1 work for you?

**Comment by infinitnet** [comment]
I just tried it and 0.9.1 works perfectly fine. Thank you for your hard work and the neat additions in the new version!
