### ISSUE TITLE
problem with linux version

### ISSUE THREAD

**Issue by youlouk** [groovesquid/groovesquid#55]
Hi,

I'm trying to listen and download some music in my linux (ubuntu 14.04)

This is the error message : 

GRAVE: error download track com.groovesquid.model.Track@1b79ea6f
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
	at java.util.regex.Matcher.reset(Matcher.java:308)
	at java.util.regex.Matcher.<init>(Matcher.java:228)
	at java.util.regex.Pattern.matcher(Pattern.java:1088)
	at com.groovesquid.service.hoster.Deezer.getDownloadUrl(Deezer.java:88)
	at com.groovesquid.service.DownloadService$DownloadTask.run(DownloadService.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)

Can you help me?

Ask me if you need more information.
Thank you for your job :).

**Comment by gbhrdt** [comment]
The problem is, that the API where we get the Deezer songs from is currently down. For now, please try the latest release (https://github.com/groovesquid/groovesquid/releases/tag/v0.9.3) which skips Deezer, if it is not available and downloads the songs from other Sources.

**Comment by youlouk** [comment]
I try and it's work. Thank you!!
